// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: client.sql

package db

import (
	"context"
)

const createClient = `-- name: CreateClient :one
insert into client (email, password_hash, name)
values ($1, $2, $3)
returning id, name, email, password_hash
`

type CreateClientParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.Email, arg.PasswordHash, arg.Name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
select id, name, email, password_hash from client
where email = $1
`

func (q *Queries) GetClient(ctx context.Context, email string) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, email)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}
