// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	uuid "github.com/google/uuid"
)

type User struct {
	PhoneNumber string    `json:"phone_number"`
	ID          uuid.UUID `json:"id"`
	FirstName   string    `json:"first_name"`
	SecondName  string    `json:"second_name"`
}
