// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
insert into users (email, first_name, second_name, password_hash)
values ($1, $2, $3, $4)
`

type CreateUserParams struct {
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	SecondName   string `json:"second_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.SecondName,
		arg.PasswordHash,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
select id, email, first_name, second_name, password_hash from users
where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.SecondName,
		&i.PasswordHash,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set 
    first_name = coalesce($1, first_name),
    second_name = coalesce($2, second_name),
    email = coalesce($3, email)
where id = $4
returning id, email, first_name, second_name, password_hash
`

type UpdateUserParams struct {
	FirstName  *string   `json:"first_name"`
	SecondName *string   `json:"second_name"`
	Email      *string   `json:"email"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.SecondName,
		arg.Email,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.SecondName,
		&i.PasswordHash,
	)
	return i, err
}
