// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (phone_number, first_name, second_name)
values ($1, $2, $3)
returning phone_number, id, first_name, second_name
`

type CreateUserParams struct {
	PhoneNumber string `json:"phone_number"`
	FirstName   string `json:"first_name"`
	SecondName  string `json:"second_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneNumber, arg.FirstName, arg.SecondName)
	var i User
	err := row.Scan(
		&i.PhoneNumber,
		&i.ID,
		&i.FirstName,
		&i.SecondName,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
select phone_number, id, first_name, second_name from users
where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.PhoneNumber,
		&i.ID,
		&i.FirstName,
		&i.SecondName,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set 
    first_name = coalesce($1, first_name),
    second_name = coalesce($2, second_name),
    phone_number = coalesce($3, phone_number)
where id = $4
returning phone_number, id, first_name, second_name
`

type UpdateUserParams struct {
	FirstName   *string   `json:"first_name"`
	SecondName  *string   `json:"second_name"`
	PhoneNumber *string   `json:"phone_number"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.SecondName,
		arg.PhoneNumber,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.PhoneNumber,
		&i.ID,
		&i.FirstName,
		&i.SecondName,
	)
	return i, err
}
