// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
select id, username, firstname, course, faculty from users
where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Firstname,
		&i.Course,
		&i.Faculty,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set 
    firstname = coalesce($1, firstname),
    username = coalesce($2, username),
    course = coalesce($3, course),
    faculty = coalesce($4, faculty)
where id = $5
returning id, username, firstname, course, faculty
`

type UpdateUserParams struct {
	Firstname *string   `json:"firstname"`
	Username  *string   `json:"username"`
	Course    *string   `json:"course"`
	Faculty   *string   `json:"faculty"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Firstname,
		arg.Username,
		arg.Course,
		arg.Faculty,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Firstname,
		&i.Course,
		&i.Faculty,
	)
	return i, err
}
